url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Rowan Future" # the name of your site, e.g. ACME Corp.
lang: "EN-US"
main-css: "/assets/css/main.css"

permalink: pretty

collections:
  games:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
    order:
      - Starline Horizon.md
      - Witchie.md
      - Sleef 2.md